### ISSUE TITLE
How to open menu

### ISSUE THREAD

**Issue by ArchknightO-O** [Strigger7/StarRail-S-GC-Release#1]
I know this isn't the main repo, but when I run the .exe it asks me to select the launcher, so I do. But I can get the mod menu to appear in game. How do I get it to appear in game. As far as I remember the keybind should be f1. Any help is appreciated!

**Comment by ArchknightO-O** [comment]
If you don't have a solution it would be helpful if you guys could show what steps you used.

**Comment by ArchknightO-O** [comment]
For those who have the same issue the game is located in 
C:\Program Files\Star Rail\Games\StarRail.exe
Do not select the launcher. That was the issue.

**Comment by Strigger7** [comment]
the original source is already outdated, you wont be able to use it
